# Generated by Django 4.2.4 on 2023-08-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_person_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='on_chat',
            field=models.BooleanField(default=False),
        ),
    ]
