# Generated by Django 4.2.4 on 2023-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_interest_remove_person_interests_person_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.AddField(
            model_name='person',
            name='interests',
            field=models.CharField(default='React', max_length=50),
            preserve_default=False,
        ),
    ]
