# Generated by Django 4.2.4 on 2023-08-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_person_interests_delete_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='interests',
        ),
        migrations.AddField(
            model_name='person',
            name='interests',
            field=models.ManyToManyField(to='chat.interest'),
        ),
    ]
